"""add task status metrics

Revision ID: ba7c71a0df1a
Revises: 9e26d51533ed
Create Date: 2026-01-06 14:38:19.120536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba7c71a0df1a'
down_revision: Union[str, Sequence[str], None] = '9e26d51533ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_statuses', sa.Column('metrics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_statuses', 'metrics')
    # ### end Alembic commands ###
